version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails server --port=3000 --binding='0.0.0.0'
    volumes:
      - .:/web
    ports:
      - "3000:3000"
    depends_on:
      - db

